---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-ad-service"
  labels:
    app.kubernetes.io/name: ad-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ad-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  ports:
    - targetPort: 8082
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: "{{ .Chart.Name }}-ad-service"
  labels:
    app: ad-service
    app.kubernetes.io/name: ad-service
    app.kubernetes.io/component: ad-service
    app.kubernetes.io/version: "{{ .Values.unguard.adService.tag }}"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  name: "{{ .Chart.Name }}-ad-service"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ad-service
      app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ad-service
        app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: ad-service
          image: "{{ .Values.unguard.adService.image }}:{{ .Values.unguard.adService.tag }}"
          ports:
            - containerPort: 8082
          env:
            - name: JAEGER_SERVICE_NAME
              value: "unguard-ad-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: SERVER_PORT
              value: "8082"
            - name: API_PATH
              value: "/ad-service"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "unguard-user-auth-service"
            - name: DT_RELEASE_VERSION
              value: "{{ .Values.unguard.adService.tag }}"
            - name: DT_RELEASE_BUILD_VERSION
              value: "{{ .Values.unguard.adService.tag }}"
            - name: DT_RELEASE_PRODUCT
              value: "{{ .Chart.Name }}"
            - name: DT_RELEASE_STAGE
              value: "{{ .Release.Namespace }}"

