---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-frontend"
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  ports:
    - targetPort: 3000
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-frontend"
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "{{ .Values.unguard.frontend.tag }}"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.unguard.frontend.image }}:{{ .Values.unguard.frontend.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: JAEGER_SERVICE_NAME
              value: "unguard-frontend"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: MICROBLOG_SERVICE_ADDRESS
              value: "unguard-microblog-service"
            - name: PROXY_SERVICE_ADDRESS
              value: "unguard-proxy-service"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "unguard-user-auth-service"
            - name: AD_SERVICE_ADDRESS
              value: "unguard-ad-service"
            - name: FRONTEND_BASE_PATH
              value: "/ui"
            - name: AD_SERVICE_BASE_PATH
              value: "/ad-service"
            - name: DT_RELEASE_VERSION
              value: "{{ .Values.unguard.frontend.tag }}"
            - name: DT_RELEASE_BUILD_VERSION
              value: "{{ .Values.unguard.frontend.tag }}"
            - name: DT_RELEASE_PRODUCT
              value: "{{ .Chart.Name }}"
            - name: DT_RELEASE_STAGE
              value: "{{ .Release.Namespace }}"
