apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-microblog-service"
  labels:
    app.kubernetes.io/name: microblog-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: microblog-service
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  ports:
    - targetPort: 8080
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-microblog-service"
  labels:
    app.kubernetes.io/name: microblog-service
    app.kubernetes.io/component: microblog-service
    app.kubernetes.io/version: "{{ .Values.unguard.microblogService.tag }}"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microblog-service
      app.kubernetes.io/part-of: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microblog-service
        app.kubernetes.io/part-of: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: microblog-service
          image: "{{ .Values.unguard.microblogService.image }}:{{ .Values.unguard.microblogService.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAEGER_SERVICE_NAME
              value: "unguard-microblog-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: REDIS_SERVICE_ADDRESS
              value: "unguard-redis"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "unguard-user-auth-service"
            - name: DT_RELEASE_VERSION
              value: "{{ .Values.unguard.microblogService.tag }}"
            - name: DT_RELEASE_BUILD_VERSION
              value: "{{ .Values.unguard.microblogService.tag }}"
            - name: DT_RELEASE_PRODUCT
              value: "{{ .Chart.Name }}"
            - name: DT_RELEASE_STAGE
              value: "{{ .Release.Namespace }}"
